In [1]:
test = "test"

In [2]:
test

'test'

In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.2.5


In [12]:
arr = np.random.randint(0, 100, size=(3, 3))
print(arr)

[[66 75 28]
 [30 82  5]
 [88 68 25]]


In [13]:
arr1 = np.random.randint(0, 100, size=(1, 3))
print(arr1)

[[ 9 32 84]]


In [15]:
result = np.dot(arr1, arr)

In [16]:
print(np.dot(arr1, arr))

[[8946 9011 2512]]
