In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([5,3])

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [4, 9, 6]])

In [5]:
print("Shape:", arr1.shape) 
print("Shape:", arr2.shape) 
print("Shape:", arr3.shape) 
    
print("Dimensions:", arr1.ndim)      
print("Dimensions:", arr2.ndim) 
print("Dimensions:", arr3.ndim) 

print("Data type:", arr1.dtype)     
print("Data type:", arr2.dtype) 
print("Data type:", arr3.dtype) 

print("Size:", arr1.size)    
print("Size:", arr2.size) 
print("Size:", arr3.size) 

print("Type:", type(arr1))  
print("Type:", type(arr2)) 
print("Type:", type(arr3)) 


Shape: (2,)
Shape: (2, 3)
Shape: (3, 3)
Dimensions: 1
Dimensions: 2
Dimensions: 2
Data type: int64
Data type: int64
Data type: int64
Size: 2
Size: 6
Size: 9
Type: <class 'numpy.ndarray'>
Type: <class 'numpy.ndarray'>
Type: <class 'numpy.ndarray'>


In [6]:
df = pd.DataFrame(arr3, columns=["A", "B", "C"])

In [7]:
df

A  B  C
0  1  2  3
1  4  5  6
2  4  9  6

In [8]:
arr = np.ones((10,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
zerosArr = np.zeros((7, 2, 3))
zerosArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
rangeArr = np.arange(0,100, 3)
rangeArr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
randArr= np.random.randint(0, 11, size=(7,2))
randArr

array([[ 0,  9],
       [ 3,  5],
       [ 9,  8],
       [ 9,  0],
       [ 9,  6],
       [ 1,  3],
       [10,  1]])

In [12]:
floatsArr = np.random.rand(3,5)
floatsArr

array([[0.09258767, 0.75857043, 0.0226566 , 0.98661473, 0.82116142],
       [0.05339514, 0.0029667 , 0.9500322 , 0.67683198, 0.75842732],
       [0.8619845 , 0.17693349, 0.18306424, 0.9059377 , 0.00614318]])

In [13]:
np.random.seed(42)
seedArray = np.random.randint(0, 11, size= (4,6))
seedArray

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

In [14]:
#14
seedArray[0]

array([ 6,  3, 10,  7,  4,  6])

In [15]:
#15
seedArray[:2]

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7]])

In [16]:
# 16 Get the first 2 values of the first 2 rows of the latest array
seedArray [:2, :2]

array([[6, 3],
       [9, 2]])

In [17]:
# 17 Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_array = np.random.randint(0, 11, size=(3, 5))
ones_array = np.ones((3, 5), dtype=int)

random_array



array([[ 0,  9,  5,  8,  0],
       [10, 10,  9,  2,  6],
       [ 3,  8,  2,  4,  2]])

In [18]:
ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# Add the two arrays together

result = random_array + ones_array
result

array([[ 1, 10,  6,  9,  1],
       [11, 11, 10,  3,  7],
       [ 4,  9,  3,  5,  3]])

In [20]:
# Create another array of ones of shape (5, 3)
ones_array2 = np.ones((5, 3), dtype=int)
ones_array2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
sum_arrays = ones_array + ones_array2.T
sum_arrays

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [22]:
arrays = ones_array - ones_array2.T
arrays

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
arrays = ones_array * ones_array2.T
arrays

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
arrays = random_array ** random_array
arrays

array([[          1,   387420489,        3125,    16777216,           1],
       [10000000000, 10000000000,   387420489,           4,       46656],
       [         27,    16777216,           4,         256,           4]])

In [25]:
# Find the mean of the latest array using np.mean()
arrmean = np.mean(arrays)
arrmean

np.float64(1387229699.2)

In [26]:
# Find the maximum of the latest array using np.max()
maxArr = np.max(arrays)
maxArr

np.int64(10000000000)

In [27]:
# Find the minimum of the latest array using np.min()
minArr = np.min(arrays)
minArr

np.int64(1)

In [28]:
# Find the standard deviation of the latest array
std_dev = np.std(arrays)
std_dev

np.float64(3380677039.170272)

In [29]:
# Find the variance of the latest array
variance = np.var(arrays)
variance

np.float64(1.1428977243173075e+19)

In [30]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = arrays.reshape(3, 5, 1)
reshaped_array


array([[[          1],
        [  387420489],
        [       3125],
        [   16777216],
        [          1]],

       [[10000000000],
        [10000000000],
        [  387420489],
        [          4],
        [      46656]],

       [[         27],
        [   16777216],
        [          4],
        [        256],
        [          4]]])

In [31]:
# Transpose the latest array
transposed_array = reshaped_array.transpose(1, 0, 2)
print("Transposed array shape:", transposed_array.shape)
print("Transposed array:\n", transposed_array)


Transposed array shape: (5, 3, 1)
Transposed array:
 [[[          1]
  [10000000000]
  [         27]]

 [[  387420489]
  [10000000000]
  [   16777216]]

 [[       3125]
  [  387420489]
  [          4]]

 [[   16777216]
  [          4]
  [        256]]

 [[          1]
  [      46656]
  [          4]]]


In [32]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

array_3x3 = np.random.randint(0, 11, size=(3, 3))

array_3x2 = np.random.randint(0, 11, size=(3, 2))

print("Array 3x3:\n", array_3x3)
print("\nArray 3x2:\n", array_3x2)


Array 3x3:
 [[6 4 8]
 [6 1 3]
 [8 1 9]]

Array 3x2:
 [[8 9]
 [4 1]
 [3 6]]


In [33]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array1 = np.random.randint(0, 11, size=(4, 3))
random_array2 = np.random.randint(0, 11, size=(4, 3))
random_array1


array([[7, 2, 0],
       [3, 1, 7],
       [3, 1, 5],
       [5, 9, 3]])

In [34]:
random_array2

array([[5, 1, 9],
       [1, 9, 3],
       [7, 6, 8],
       [7, 4, 1]])

In [35]:
dot_result = np.dot(random_array1, random_array2.T)
dot_result

array([[ 37,  25,  61,  57],
       [ 79,  33,  83,  32],
       [ 61,  27,  67,  30],
       [ 61,  95, 113,  74]])

In [36]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
# Compare the two arrays with '>'

array_a = np.random.randint(0, 11, size=(3, 3))
array_b = np.random.randint(0, 11, size=(3, 3))


comparison = array_a > array_b

print("Array A:\n", array_a)
print("\nArray B:\n", array_b)
print("\nA > B:\n", comparison)


Array A:
 [[4 7 9]
 [8 8 0]
 [8 6 8]]

Array B:
 [[ 7  0  7]
 [ 7 10  2]
 [ 0  7  2]]

A > B:
 [[False  True  True]
 [ True False False]
 [ True False  True]]


In [37]:
# Compare the two arrays with '>='

comparison2 = array_a >= array_b
comparison2

array([[False,  True,  True],
       [ True, False, False],
       [ True, False,  True]])

In [38]:
# Find which elements of the first array are greater than 7

greater_than_7 = array_a > 7

print("Array A:\n", array_a)
print("\nElements > 7 (Boolean mask):\n", greater_than_7)
print("\nValues > 7:\n", array_a[greater_than_7])

Array A:
 [[4 7 9]
 [8 8 0]
 [8 6 8]]

Elements > 7 (Boolean mask):
 [[False False  True]
 [ True  True False]
 [ True False  True]]

Values > 7:
 [9 8 8 8 8]


In [39]:
# Sort one of the arrays you just created in ascending order

sorted_array = np.sort(array_a)

print("Original Array A:\n", array_a)
print("\nSorted Array A (row-wise):\n", sorted_array)


Original Array A:
 [[4 7 9]
 [8 8 0]
 [8 6 8]]

Sorted Array A (row-wise):
 [[4 7 9]
 [0 8 8]
 [6 8 8]]


In [40]:
sorted_indices = np.argsort(array_a, axis=1)

print("Array A:\n", array_a)
print("\nSorted indices (row-wise):\n", sorted_indices)
#Each row in sorted_indices shows positions of elements in sorted order

Array A:
 [[4 7 9]
 [8 8 0]
 [8 6 8]]

Sorted indices (row-wise):
 [[0 1 2]
 [2 0 1]
 [1 0 2]]


In [41]:
# Find the index with the maximum value in one of the arrays you've created
# Find the index with the minimum value in one of the arrays you've created

max_position = np.unravel_index(np.argmax(array_a), array_a.shape)
print("Row, Column index of a max value:", max_position)

min_position = np.unravel_index(np.argmin(array_a), array_a.shape)
print("Row, Column index of a min value:", max_position)

max_position
min_position


Row, Column index of a max value: (np.int64(0), np.int64(2))
Row, Column index of a min value: (np.int64(0), np.int64(2))


(np.int64(1), np.int64(2))

In [42]:
max_pos = np.unravel_index(np.argmax(array_a), array_a.shape)
min_pos = np.unravel_index(np.argmin(array_a), array_a.shape)

print("Max value position:", tuple(map(int, max_pos)))
print("Min value position:", tuple(map(int, min_pos)))



Max value position: (0, 2)
Min value position: (1, 2)


In [43]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


# Example array (or use your existing array_a)
# array_a = np.random.randint(0, 11, size=(3, 3))

max_indices_per_row = np.argmax(array_a, axis=1)

print("Array A:\n", array_a)
print("\nIndex of max value in each row:\n", max_indices_per_row)


Array A:
 [[4 7 9]
 [8 8 0]
 [8 6 8]]

Index of max value in each row:
 [2 0 0]


In [45]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices_per_column = np.argmin(array_a, axis=0)

print("Array A:\n", array_a)
print("\nIndex of min value in each column:\n", min_indices_per_column)


Array A:
 [[4 7 9]
 [8 8 0]
 [8 6 8]]

Index of min value in each column:
 [0 2 1]


In [46]:
# Create an array of normally distributed random numbers

# Create a 2D array with shape (3, 4)
normal_array = np.random.randn(3, 4)

print("Normally distributed array:\n", normal_array)


Normally distributed array:
 [[ 0.47604259  1.30366127  0.21158701  0.59704465]
 [-0.89633518 -0.11198782  1.46894129 -1.12389833]
 [ 0.9500054   1.72651647  0.45788508 -1.68428738]]


In [47]:
# Create an array with 10 evenly spaced numbers between 1 and 100

evenly_spaced = np.linspace(1, 100, 10)

print("Evenly spaced numbers:\n", evenly_spaced)


Evenly spaced numbers:
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
